type ArtistAlias = Record<string, string>;

export const ARTIST_ALIAS_DICTIONARY: ArtistAlias = {
	"10CM": "10cm",
	BUZZ: "버즈",
	Buzz: "버즈",
	"An Nyeong": "#안녕",
	BEN: "벤",
	BIBI: "비비 (BIBI)",
	"Choi Young Kwan (Dr. Shinbaram Choi)": "최영관 (신바람 최박사)",
	DAY6: "DAY6(데이식스)",
	"DK(DECEMBER)": "DK(디셈버)",
	"Do Hyeok Lim": "임도혁",
	FTISLAND: "FTISLAND(FT아일랜드)",
	"Lee Hong Ki (FTISLAND)": "FTISLAND(이홍기)",
	"Lee Hong Gi": "FTISLAND(이홍기)",
	Flower: "플라워",
	Gitae: "순순희 (기태)",
	"HYB (Huh Gak，Shin Yong Jae，Onestar)": "허용별 (허각，신용재，임한별)",
	"Han dong geun": "한동근",
	"Huh Gak": "허각",
	"Hwagok-dong green frog": "화곡동 청개구리",
	"Hwang In Wook": "황인욱",
	"M.C the MAX(엠씨더맥스)": "M.C The Max",
	"M.C the MAX": "M.C The Max",
	"M.C the Max": "M.C The Max",
	"엠씨더맥스 (M.C The Max)": "M.C The Max",
	"엠씨더맥스 / M.C The Max": "M.C The Max",
	"ISU(이수)": "M.C The Max (이수)",
	"Im Chang-jung": "임창정",
	"JANG DEOK CHEOL": "장덕철",
	"JANG DEOK CHEOL(장덕철)": "장덕철",
	"JUNG DONG HA": "정동하",
	"Jung Dong Ha": "정동하",
	"Jang Beom June": "장범준",
	"Jeon Gunho": "전건호",
	"Jeon Sang Keun": "전상근",
	Juho: "주호",
	"Jung Seung Hwan": "정승환",
	"K.will": "케이윌",
	"KIM DONG RYUL": "김동률",
	"KWAK JIN EON(곽진언)": "곽진언",
	"Kim Dong Myung": "김동명",
	"Kim Feel": "김필",
	"Kim Jung Min": "김정민",
	"Kim Kyung Ho": "김경호",
	"Ko Yujin (Flower)": "플라워(고유진)",
	"Lee Juck": "이적",
	"Lee Seung Gi(이승기)": "이승기",
	"MSG WANNABE TOP8": "MSG WANNABE",
	"MSG WANNABE (M.O.M)": "MSG WANNABE",
	Maktub: "마크툽",
	NAUL: "나얼",
	"Nerd Connection": "너드커넥션 (Nerd Connection)",
	Nilo: "닐로",
	Onestar: "임한별",
	"Parc Jae Jung": "박재정",
	"Park Hyo Shin": "박효신",
	"Roy Kim": "로이킴",
	"로이킴 Roy Kim": "로이킴",
	"Sung Si Kyung": "성시경",
	"Song I Han": "송이한",
	"The Black Skirts": "검정치마 (The Black Skirts)",
	"The One": "더 원",
	Tophyun: "탑현",
	"URBAN ZAKAPA": "어반자카파",
	"YB (윤도현 밴드)": "윤도현",
	YB: "윤도현",
	"Yoon Do Hyun": "윤도현",
	Yarn: "얀",
	"곽진언 Kwak Jinon": "곽진언",
	"국카스텐(Guckkasten)": "하현우 (국카스텐)",
	"더 크로스 / The Cross": "더 크로스",
	"플라워(고유진)": "플라워",
};
