import { INativePlaylistItem } from "@/models/native-playlist-item";

interface IMusic {
	singer?: string;
	title?: string;
}

type MusicDic = Record<string, IMusic>;

type SingerAlias = Record<string, string>;

export default class PlaylistItem {
	private __native: INativePlaylistItem;

	constructor(item: INativePlaylistItem) {
		this.__native = item;
	}

	isAutoGenerated() {
		return this.__native.snippet.description.includes(
			"Auto-generated by YouTube."
		);
	}

	getVideoId() {
		return this.__native.snippet.resourceId.videoId;
	}

	getSinger() {
		if (!this.isAutoGenerated()) {
			return this.__native.snippet.videoOwnerChannelTitle.trim();
		}

		return this.__native.snippet.description
			.split("\n\n")[1]
			.split("·")[1]
			.trim();
	}

	getTitle() {
		return this.__native.snippet.title;
	}
}

export function getItemName(item: PlaylistItem, dic: MusicDic): string {
	return dic[item.getVideoId()].title || item.getTitle();
}

export function getItemSinger(
	item: PlaylistItem,
	dic: MusicDic,
	singerAliasDic: SingerAlias
): string {
	const singer = dic[item.getVideoId()].singer || item.getSinger();

	return singerAliasDic[singer] || singer;
}
